
#adds records to a hep_generated_YEAR.csv file for colonies where there were no nests in a particular year.
# user supplies year (seas), and the colony identifier code
# relies on a particular folder structure where files are saved
# for now these files and their paths are:
# projects/HEP/hep_generated_YEAR.csv -- this is generated by the HEPscreen to HEP code
# projects/HEP/tbl_HEPSites.csv  -- this one is pulled directly from the HEP database

library(plyr)
library(tidyverse)

#
setwd("C:/Users/scott.jennings/Documents/") 

# function to import data
import.year.hep.generated=function(seas){
  hep=read.csv(paste("projects/HEP/",paste("hep_generated", seas, sep="_"), ".csv", sep=""))
  return(hep)
}
# call the import function
hep=import.year.hep.generated(2017)

# specify season
seas = c("2016", "2017")
# and single colony 
#cols = "1"
# or multiple colonies
cols = c("1", "53", "53.1")


blank_maker = function(col.code){
spp <- c("GBHE", "GREG", "SNEG", "BCNH", "CAEG", "DCCO")
sites <- read.csv("projects/HEP/tbl_HEPSites.csv")  
site <- sites %>% filter(Code == col.code) %>% select(Site_Name, Code) %>% droplevels()
  
frrg = data.frame(spp, 
                  site)%>% 
  select(CODE = Code, SPECIES = spp, SITE = Site_Name) %>% 
  mutate(TOTALSPECIES = 0,
         NUMBERVISITS = 0,
         TOTALHOURS = 0,
         PEAKACTVNSTS = 0,
         FOCALNESTS = 0,
         FOCFAILURE = 0,
         YEAR = as.numeric(seas))

return(frrg)  
}
# call the function within ldply to account fo rmultiple colonies
blanks <- ldply(cols, blank_maker)


# remove Code - Species combos that already exist in hep
blanks_sub <- anti_join(blanks, hep, by = c("SPECIES", "CODE"))

# then append the blanks to hep
heper <- bind_rows(hep, blanks_sub)



write_csv(heper, paste("Projects/HEP/hep_generated_", seas, "_blanks.csv", sep=""))
